import { DataTypes, QueryInterface } from "sequelize"
import { Migration } from '../migration'
import moment from 'moment'

const up: Migration = async ({context} : { context: QueryInterface}) => {
    await context.bulkInsert('User', [
        {
            id: 5009,
            name: 'Henrietta Schlum',
            email: 'henrietta@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5010,
            name: 'James Saka',
            email: 'jamiesaka@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5011,
            name: 'Joy Eyime',
            email: 'joyezime@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5012,
            name: 'Lemao Oganiru',
            email: 'oganiru@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5013,
            name: 'Johnson Omo',
            email: 'johnsonomo@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5014,
            name: 'Lynda Caritas',
            email: 'lyndac@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5015,
            name: 'Khadija Omole',
            email: 'khadi@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5016,
            name: 'Francis akime',
            email: 'francis@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5017,
            name: 'Stanley Obo',
            email: 'stanley@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5018,
            name: 'Bey Nicki',
            email: 'bey@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5019,
            name: 'Messi Frank',
            email: 'messi@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5020,
            name: 'Bichhee Owa',
            email: 'bichee@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5021,
            name: 'Classina Nalo',
            email: 'classina@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5022,
            name: 'Queen Ojo',
            email: 'Queenojo@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5023,
            name: 'Soma Savage',
            email: 'somalina@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5024,
            name: 'Akin Suppi',
            email: 'akinsuppi@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5025,
            name: 'Abinon Lukas',
            email: 'abinnon@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5026,
            name: 'Heytarade Teso',
            email: 'heyta@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5027,
            name: 'Konnais Agbo',
            email: 'konnias@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5028,
            name: 'Grace Amy Richard',
            email: 'graceamy@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5029,
            name: 'Chessie Kong',
            email: 'chessie@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5030,
            name: 'Ringoda Salusi',
            email: 'ringoda@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5031,
            name: 'Passie Bodizo',
            email: 'passie@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5032,
            name: 'Ruth Etike',
            email: 'ruth@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5033,
            name: 'Justin Onaghise',
            email: 'justin@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5034,
            name: 'Maifi Waifi',
            email: 'maifi@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
        {
            id: 5035,
            name: 'Skye Blau',
            email: 'skye@gmail.com',
            password: 'apassword',
            userType: 'therapist',
            createdAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
            updatedAt: moment(Date()).format("YYYY-MM-DD HH:mm:ss"),
        },
    ])
}

const down: Migration  = async ({context} : { context: QueryInterface}) => {
	await context.bulkDelete('User', { userType: 'therapist'})
};

export { up, down }

